# The name of the environment matching the repository name
name: agis
# I prefer conda-forge packages for my projects
channels:
- conda-forge
- defaults
# Start with Python and include everything you need
dependencies:
- python=3.7
- pip
- numpy
- numba
- matplotlib
...
